### ISSUE TITLE
Opening app should not have focus on search field

### ISSUE THREAD

**Issue by loffa** [wsv-accidis/in-sangbok#1]
When opening the app, the search field have focus and the keyboard is open. The keyboard should be closed when opening the app.

**Comment by wsv-accidis** [comment]
This behavior is intentional. I am assuming that in most cases the user wants to find a specific song, so I am saving them one click by showing the keyboard directly. If this turns out to be wrong (users do not use the app this way), I will change it.

I have not found any official Android style document that says whether the keyboard should be open or not on activity start. The current behavior is the default; I'm not forcing the keyboard open/closed.
